name: Rust Build CI

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  docker:
    name: push docker image to hub
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nihaopaul/forward-auth-rust

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          # tags: nihaopaul/forward-auth:latest
